const stations = [ 
    {"id":  0, "x": 0, "y": 0, "type": "A", "train": false, "side": "Buda", "district":  0},
    {"id":  1, "x": 2, "y": 0, "type": "B", "train": false, "side": "Buda", "district":  1},
    {"id":  2, "x": 4, "y": 0, "type": "D", "train": false, "side": "Buda", "district":  2},
    {"id":  3, "x": 6, "y": 0, "type": "D", "train": false, "side": "Pest", "district":  2},
    {"id":  4, "x": 7, "y": 0, "type": "B", "train": false, "side": "Pest", "district":  3},
    {"id":  5, "x": 9, "y": 0, "type": "C", "train": false, "side": "Pest", "district":  4},
    {"id":  6, "x": 0, "y": 1, "type": "D", "train": false, "side": "Buda", "district":  1},
    {"id":  7, "x": 1, "y": 1, "type": "B", "train": false, "side": "Buda", "district":  1},
    {"id":  8, "x": 5, "y": 1, "type": "A", "train": false, "side": "Buda", "district":  2},
    {"id":  9, "x": 8, "y": 1, "type": "C", "train": true , "side": "Pest", "district":  3},
    {"id": 10, "x": 9, "y": 1, "type": "A", "train": false, "side": "Pest", "district":  3},
    {"id": 11, "x": 2, "y": 2, "type": "D", "train": false, "side": "Buda", "district":  1},
    {"id": 12, "x": 4, "y": 2, "type": "D", "train": false, "side": "Buda", "district":  2},
    {"id": 13, "x": 5, "y": 2, "type": "D", "train": false, "side": "Buda", "district":  3},
    {"id": 14, "x": 6, "y": 2, "type": "C", "train": false, "side": "Pest", "district":  3},
    {"id": 15, "x": 9, "y": 2, "type": "D", "train": false, "side": "Pest", "district":  4},
    {"id": 16, "x": 0, "y": 3, "type": "C", "train": false, "side": "Buda", "district":  5},
    {"id": 17, "x": 2, "y": 3, "type": "B", "train": false, "side": "Buda", "district":  5},
    {"id": 18, "x": 3, "y": 3, "type": "C", "train": false, "side": "Buda", "district":  6},
    {"id": 19, "x": 7, "y": 3, "type": "A", "train": false, "side": "Pest", "district":  7},
    {"id": 20, "x": 8, "y": 3, "type": "D", "train": false, "side": "Pest", "district":  7},
    {"id": 21, "x": 0, "y": 4, "type": "B", "train": false, "side": "Buda", "district":  5},
    {"id": 22, "x": 3, "y": 4, "type": "A", "train": false, "side": "Buda", "district":  6},
    {"id": 23, "x": 4, "y": 4, "type": "B", "train": false, "side": "Buda", "district":  6},
    {"id": 24, "x": 5, "y": 4, "type": "C", "train": false, "side": "Pest", "district":  6},
    {"id": 25, "x": 6, "y": 4, "type": "A", "train": true , "side": "Pest", "district":  6},
    {"id": 26, "x": 9, "y": 4, "type": "A", "train": false, "side": "Pest", "district":  7},
    {"id": 27, "x": 0, "y": 5, "type": "A", "train": false, "side": "Buda", "district":  5},
    {"id": 28, "x": 2, "y": 5, "type": "C", "train": false, "side": "Buda", "district":  5},
    {"id": 29, "x": 5, "y": 5, "type": "D", "train": false, "side": "Pest", "district":  6},
    {"id": 30, "x": 6, "y": 5, "type": "?", "train": false, "side": "Pest", "district":  6},
    {"id": 31, "x": 9, "y": 5, "type": "B", "train": false, "side": "Pest", "district":  7},
    {"id": 32, "x": 1, "y": 6, "type": "C", "train": false, "side": "Buda", "district":  5},
    {"id": 33, "x": 3, "y": 6, "type": "D", "train": true , "side": "Buda", "district":  6},
    {"id": 34, "x": 6, "y": 6, "type": "B", "train": false, "side": "Pest", "district":  6},
    {"id": 35, "x": 7, "y": 6, "type": "D", "train": false, "side": "Pest", "district":  7},
    {"id": 36, "x": 8, "y": 6, "type": "C", "train": true , "side": "Pest", "district":  7},
    {"id": 37, "x": 0, "y": 7, "type": "B", "train": false, "side": "Buda", "district":  9},
    {"id": 38, "x": 3, "y": 7, "type": "A", "train": false, "side": "Buda", "district": 10},
    {"id": 39, "x": 4, "y": 7, "type": "B", "train": false, "side": "Buda", "district": 10},
    {"id": 40, "x": 6, "y": 7, "type": "B", "train": false, "side": "Pest", "district": 10},
    {"id": 41, "x": 9, "y": 7, "type": "A", "train": false, "side": "Pest", "district": 11},
    {"id": 42, "x": 1, "y": 8, "type": "A", "train": false, "side": "Buda", "district":  9},
    {"id": 43, "x": 2, "y": 8, "type": "B", "train": false, "side": "Buda", "district":  9},
    {"id": 44, "x": 5, "y": 8, "type": "C", "train": false, "side": "Buda", "district": 10},
    {"id": 45, "x": 8, "y": 8, "type": "D", "train": false, "side": "Pest", "district": 11},
    {"id": 46, "x": 0, "y": 9, "type": "D", "train": false, "side": "Buda", "district":  8},
    {"id": 47, "x": 2, "y": 9, "type": "C", "train": false, "side": "Buda", "district":  9},
    {"id": 48, "x": 3, "y": 9, "type": "A", "train": true , "side": "Buda", "district": 10},
    {"id": 49, "x": 6, "y": 9, "type": "D", "train": false, "side": "Buda", "district": 10},
    {"id": 50, "x": 7, "y": 9, "type": "A", "train": false, "side": "Pest", "district": 11},
    {"id": 51, "x": 8, "y": 9, "type": "C", "train": false, "side": "Pest", "district": 11},
    {"id": 52, "x": 9, "y": 9, "type": "B", "train": false, "side": "Pest", "district": 12}
];

const lines = [
    {"id": 0, "name": "M1", "color": "#FFD800", "start": 19},
    {"id": 1, "name": "M2", "color": "#E41F18", "start": 28},
    {"id": 2, "name": "M3", "color": "#005CA5", "start":  3},
    {"id": 3, "name": "M4", "color": "#4CA22F", "start": 39}
];

export { stations, lines };